/*Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.  */

import UIKit




var number1 = 1
var number2 = 2
var total  = 0

var answerSum = 0




for number in 1...400 {
    
    total = number1 + number2
    
    //make sure we don't exceed 4 million
    
    if(total > 4000000){
        break
    }
    
    
    number1 = number2
    
    number2 = total
    
    print(total)
    
    
    if(total % 2 == 0) {
        //print("\(total) is even")
        
        answerSum += total
        
    }
    
    
    
}

answerSum += 2

print("\(answerSum) is final")
